add check

diff --git a/tests/ami/scripts/partial/restart_agent_and_remove_logs.ps1.j2 b/tests/ami/scripts/partial/restart_agent_and_remove_logs.ps1.j2
--- a/tests/ami/scripts/partial/restart_agent_and_remove_logs.ps1.j2
+++ b/tests/ami/scripts/partial/restart_agent_and_remove_logs.ps1.j2
@@ -4,8 +4,14 @@ echo ""
 
 scalyr-agent-2 stop;
 
-
 Start-Sleep 2
+
+Get-Process -Name ScalyrAgentService -ErrorAction Continue
+
+if ($?)
+{
+    Write-Error -Message "The Scalyr agent is still running even after the the service has been stopped." -ErrorAction Stop
+}
 
 echo "Tailling last 50 lines of log"
 echo "-----------------------------"
