Small smoke test improvements (#456)
* Fix packaging smoke tests.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -247,13 +247,9 @@ commands:
             # when job runs from CircleCi servers, the 'AGENT_HOST_NAME' is not set, so 'CIRCLE_BUILD_NUM' is used.
             # when job runs locally, the 'CIRCLE_BUILD_NUM' is not set, so 'AGENT_HOST_NAME' is used.
             export CIRCLE_BUILD_NUM=${CIRCLE_BUILD_NUM}${AGENT_HOST_NAME}
-
             export AGENT_HOST_NAME=agent-smoke-standalone-<< parameters.python_version >>-${CIRCLE_BUILD_NUM}
-            tox -e<< parameters.tox_target >>
 
-            # copy log files to artifacts directory.
-            mkdir -p ~/artifacts
-            cp ~/scalyr-agent-dev/log/agent.log ~/artifacts/agent.log
+            tox -e<< parameters.tox_target >>
       - save_cache:
           key: deps2-tox-{{ .Branch }}-<< parameters.python_version >>-venv-{{ checksum "dev-requirements.txt" }}
           paths:
@@ -261,7 +257,7 @@ commands:
 
       # NOTE: We store the logs to ease with troubleshooting / debugging
       - store_artifacts:
-          path: ~/artifacts
+          path: ~/scalyr-agent-dev/log
 
   smoke-package:
     description: "A base command for package smoke tests. It invokes tox target with name 'agent_package_smoke_test_<parameters>'"
@@ -304,12 +300,23 @@ commands:
             # when job runs from CircleCi servers, the 'AGENT_HOST_NAME' is not set, so 'CIRCLE_BUILD_NUM' is used.
             # when job runs locally, the 'CIRCLE_BUILD_NUM' is not set, so 'AGENT_HOST_NAME' is used.
             export CIRCLE_BUILD_NUM=${CIRCLE_BUILD_NUM}${AGENT_HOST_NAME}
-
             export AGENT_HOST_NAME=agent-package-smoke-<< parameters.distribution >>-<< parameters.python_version >>-${CIRCLE_BUILD_NUM}
-            tox -e agent_package_smoke_test_<< parameters.distribution >>_<< parameters.python_version >> -- --package-image-cache-path ~/agent_image
+
+            # NOTE: We don't want the build to immediately fail if tox command fails because we
+            # want to preserve the build logs as artifacts to aid with debugging
+            set +e
+            tox -eagent_package_smoke_test_<< parameters.distribution >>_<< parameters.python_version >> -- --package-image-cache-path ~/agent_image
+            EXIT_CODE=$?
+            set -e
+
             # copy log files to artifacts directory.
             mkdir -p ~/artifacts
-            docker cp scalyr_agent_smoke_<< parameters.distribution >>_<< parameters.python_version >>:/var/log/scalyr-agent-2/agent.log ~/artifacts/agent.log
+            docker cp scalyr_agent_smoke_<< parameters.distribution >>_<< parameters.python_version >>:/var/log/scalyr-agent-2 ~/artifacts/
+
+            if [ "${EXIT_CODE}" -ne "0" ]; then
+                echo "tox target failed"
+                exit 1
+            fi
 
       - save_cache:
           # save agent image to 'tar' file here, if this file is not found previously.
@@ -320,7 +327,7 @@ commands:
       - save_cache:
           key: deps2-tox-{{ .Branch }}-3.6-venv-{{ checksum "dev-requirements.txt" }}
           paths:
-            - "~/.cache/pip."
+            - "~/.cache/pip"
 
       # NOTE: We store the logs to ease with troubleshooting / debugging
       - store_artifacts:
@@ -959,22 +966,14 @@ workflows:
             - smoke-k8s
   package-smoke-tests:
     jobs:
-      - smoke-rpm-package-py3:
-          filters:
-            branches:
-              only: master
       - smoke-rpm-package-py2:
-          filters:
-            branches:
-              only: master
-      - smoke-deb-package-py3:
-          filters:
-            branches:
-              only: master
+          <<: *master_only
+      - smoke-rpm-package-py3:
+          <<: *master_only
       - smoke-deb-package-py2:
-          filters:
-            branches:
-              only: master
+          <<: *master_only
+      - smoke-deb-package-py3:
+          <<: *master_only
   benchmarks:
     jobs:
       - benchmarks-idle-agent-py-27:
@@ -995,7 +994,6 @@ workflows:
           <<: *master_only
       - benchmarks-loaded-agent-single-growing-log-file-180mb-py-27:
           <<: *master_only
-
   weekly-circle-ci-usage-report:
     triggers:
       - schedule:
