Add very simple "retry whole script on failure" logic to save us some time from manual re-runs on network and similar related failures.
NOTE: In the future we should optimize it to only retry jobs for AMI
tests which failed and not all of them.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -730,7 +730,34 @@ commands:
               export INSTALLER_SCRIPT_URL="/tmp/workspace/installScalyrAgentV2.sh"
             fi
 
-            ./scripts/circleci/run-ami-tests-in-bg.sh << parameters.test_type >>
+            set +e
+
+            max_attempts="2"
+            sleep_delay="15"
+
+            i=0
+            until [ "$i" -ge ${max_attempts} ]; do
+                echo "Running tests command"
+                ./scripts/circleci/run-ami-tests-in-bg.sh << parameters.test_type >>
+                exit_code=$?
+                if [ "${exit_code}" -eq 0 ]; then
+                    echo "Command exited with 0, breaking from the loop."
+                    break
+                else
+                    echo "Command exited with non-zero status, retrying in ${sleep_delay} seconds..."
+                fi
+                i=$((i+1))
+                sleep ${sleep_delay}
+              done
+
+              set -e
+
+              if [ "${exit_code}" -ne 0 ]; then
+                  echo "Command failed to exit with zero exit code after 2 attempts, failing (exit_code=${exit_code})"
+                  exit 1
+              fi
+
+              exit 0
       - store_artifacts:
           path: outputs
 
