Use a more robust way to determine if a provisioning has finished on output.

diff --git a/tests/ami/scripts/test_rpm.sh.j2 b/tests/ami/scripts/test_rpm.sh.j2
--- a/tests/ami/scripts/test_rpm.sh.j2
+++ b/tests/ami/scripts/test_rpm.sh.j2
@@ -20,9 +20,26 @@ set -x
 
 # Give it some time to finish provisioning process. It's possible that we can SSH in before
 # cloud-init fully finished
+CLOUD_INIT_RESULT_FILE="/run/cloud-init/result.json"
+MAX_WAIT_COUNTER=20 # we wait a maximum of 20 x 2 seconds for provision to finish
+
+WAIT_COUNTER=0
+while [ ! -f "${CLOUD_INIT_RESULT_FILE}" ] && [ ${WAIT_COUNTER} -lt ${MAX_WAIT_COUNTER} ]; do
+    echo "Waiting for cloud init provisioning to complete..."
+    ((WAIT_COUNTER=WAIT_COUNTER+1))
+    sleep 2
+done
+
+if [ ! -f "${CLOUD_INIT_RESULT_FILE}" ]; then
+    echo "Provisioning didn't finish in 40 seconds (file ${CLOUD_INIT_RESULT_FILE} doesn't exist), failing..."
+    exit 1
+fi
+
+# Give it some time to finish provisioning process. It's possible that we can SSH in before
+# cloud-init fully finished
 # TODO: A more robust and correct way would be to poll cloud-init status file until it indicates
 # provisioning has finished.
-sleep 20
+# sleep 20
 
 uname -a
 cat /etc/*-release
