test

diff --git a/.github/workflows/reusable-agent-build-linux-packages-new.yml b/.github/workflows/reusable-agent-build-linux-packages-new.yml
--- a/.github/workflows/reusable-agent-build-linux-packages-new.yml
+++ b/.github/workflows/reusable-agent-build-linux-packages-new.yml
@@ -302,19 +302,46 @@ jobs:
           driver-opts: network=host
 
       - name: Build managed package with builder '${{ matrix.name }}'
+        id: build_with_cache
         run: |
+          set +e
+          
+          EXIT_CODE=(
             python3 agent_build_refactored/scripts/builder_helper.py \
               agent_build_refactored.managed_packages.managed_packages_builders.deb-non-aio \
               --fail-on-cache-miss
-      
-      
+          )
+          
+          set -e
+          
+          case "$EXIT_CODE in
+            0)
+              echo "cache_found=false" >> "$GITHUB_OUTPUT"
+              ;;
+          
+            400)
+              echo "cache_found=true" >> "$GITHUB_OUTPUT"
+              ;;
+            *)
+              exit 1
+              ;;
+          esac
 
+#          if [ "${EXIT_CODE}" = "400"]; then
+#            echo "CACHE_IS_MISSING=true" >> "$GITHUB_OUTPUT"
+#          fi
       - name: Save packages as artifact
+        if: steps.build_with_cache.outputs.cache_found == 'true'
         uses: actions/upload-artifact@v3
         with:
           name: linux-packages-${{ matrix.name }}
           path: build
           retention-days: 1
+      
+      - name: GG
+        if: steps.build_with_cache.outputs.cache_found == 'false'
+        run:
+          echo "gggg"
 
 #  test_managed_packages:
 #    name: Test package on ${{ matrix.distro-name }}-${{ matrix.remote-machine-type }}, ${{ matrix.name }}
